[workspace]
members = [
    "crates/lockbox-crypto",
    "crates/lockbox-proto",
    "crates/lockbox-auth",
    "crates/lockbox-store",
    "server",
    "cli"
]
resolver = "3"

[workspace.package]
edition = "2024"
