[package]
name = "lockbox-store"
version = "0.1.0"
publish = false
edition = "2024"

[dependencies]
lockbox-crypto = { path = "../lockbox-crypto" }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
